# Generated by Django 3.1.2 on 2021-03-11 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='customer_requests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=200)),
                ('ph_number', models.IntegerField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('venue', models.CharField(max_length=100)),
                ('event_type', models.CharField(max_length=100)),
                ('per_request', models.TextField(max_length=500)),
            ],
        ),
    ]
