# Generated by Django 3.1.2 on 2021-03-15 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_customer_register'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_register',
            name='citizenship',
            field=models.FileField(default=1, upload_to='documents/'),
            preserve_default=False,
        ),
    ]
