# Generated by Django 3.1.2 on 2021-03-15 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_customer_register_citizenship'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer_register',
            name='citizenship',
        ),
    ]
