# Generated by Django 3.1.2 on 2021-03-20 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_auto_20210311_2018'),
        ('manager', '0005_remove_customer_register_citizenship'),
    ]

    operations = [
    ]
