# Generated by Django 3.1.7 on 2021-03-20 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_merge_20210320_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_register',
            name='ph_number',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='customer_requests',
            name='ph_number',
            field=models.IntegerField(max_length=10),
        ),
    ]
