# Generated by Django 3.1.7 on 2021-03-23 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0007_auto_20210320_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='venu',
            name='h_drinks',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='venu',
            name='nonveg_pricing',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='venu',
            name='veg_pricing',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer_register',
            name='ph_number',
            field=models.IntegerField(),
        ),
    ]
