# Generated by Django 3.1.7 on 2021-03-29 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0008_auto_20210323_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_register',
            name='u_name',
            field=models.CharField(default=123, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer_requests',
            name='ph_number',
            field=models.IntegerField(),
        ),
    ]
