# Generated by Django 3.1.7 on 2021-05-08 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0009_auto_20210329_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_requests',
            name='status',
            field=models.CharField(choices=[('A', 'Approved'), ('W', 'Withheld'), ('D', 'Denied')], default=1, max_length=1),
            preserve_default=False,
        ),
    ]
