# Generated by Django 3.1.7 on 2021-05-08 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0010_customer_requests_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_requests',
            name='request_date',
            field=models.DateField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer_requests',
            name='status',
            field=models.CharField(choices=[('A', 'Approved'), ('W', 'Withheld'), ('D', 'Denied'), ('C', 'Completed')], max_length=1),
        ),
    ]
